name: CICD

on:
  push:
    branches: [master]
  
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build docker image
        run: docker build -t kalinduwashington/weather-generator .
      - name: Publish docker image
        run: docker push kalinduwashington/weather-generator:latest
    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull kalinduwashington/weather-generator:latest
      - name: Delete old container
        run: docker rm -f weather-generator.container
      - name: Run docker container
        run: docker run -d -p 9090:9090 --name weather-generator.container kalinduwashington/weather-generator:latest